"""empty message

Revision ID: 8cda4319137c
Revises: 
Create Date: 2023-08-22 11:25:28.834276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cda4319137c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.String(length=200), nullable=False),
        sa.Column('email', sa.String(length=125), nullable=True),
        sa.Column('password', sa.String(length=125), nullable=True),
        sa.Column('first_name', sa.String(length=125), nullable=True),
        sa.Column('last_name', sa.String(length=125), nullable=True),
        sa.Column('is_staff', sa.Boolean(), nullable=True),
        sa.Column('is_superuser', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###

    op.create_table('countries',
                    sa.Column('name', sa.String(length=125), nullable=True),
                    sa.Column('id', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('cities',
                    sa.Column('name', sa.String(length=125), nullable=True),
                    sa.Column('country', sa.String(length=200), nullable=True),
                    sa.Column('id', sa.String(length=100), nullable=False),
                    sa.ForeignKeyConstraint(['country'], ['countries.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('addresses',
                    sa.Column('city', sa.String(length=200), nullable=True),
                    sa.Column('street', sa.String(length=100), nullable=True),
                    sa.Column('number', sa.String(length=10), nullable=True),
                    sa.Column('id', sa.String(length=100), nullable=False),
                    sa.ForeignKeyConstraint(['city'], ['cities.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
